spring:
  application:
    name: trading-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: '${PG_USERNAME}'
    password: '${PG_PASSWORD}'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  threads:
    virtual:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: "%5p [%t]"
  level:
    com.ibkr: info

ibkr:
  host: 127.0.0.1
  port: 7496
  client-id: 0
